### ISSUE TITLE
New methods of adding references

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/R2T2#18]
At the moment, the only way of adding a reference is by using a plain text, eg:

```python
@add_reference(short_purpose="Original implementation of R2T2", 
                  reference="Diego Alonso-Álvarez, et al. (2018, February 27). Solcore (Version 5.1.0). Zenodo. http://doi.org/10.5281/zenodo.1185316")
def my_great_function():
    pass
```

This is easy to code but is very verbose and prone to errors if the reference is not wirtten exacly the same whay in different parts of the code. 

More robust alternatives will be, for example:

- [ ] [Using the DOI](#9 )
- [ ] [Using a bibtex key](#11 )
- [ ] [Scanning the decorated function or method docstring for a `cite` key](#10 )
- [ ] [Parse code and documentation for arbitrary references](#15 )

**Comment by jezcope** [comment]
Another possibility would be to split out the different parts of the reference in the `@add_reference` decorator. For example:

```python
@add_reference(
    short_purpose="Original implementation of R2T2",
    authors="Diego Alonso-Álvarez et. al.",
    date=(2018, 2, 27),
    title="Solcore (Version 5.1.0)",
    publisher="Zenodo",
    doi="http://doi.org/10.5281/zenodo.1185316",
)
def my_function():
    # ...
```

Although perhaps in that case some or all of the metadata could be omitted and filled from the DOI metadata.
